services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: registry.gabrielkaszewski.dev/k-qr:latest
    container_name: k-qr

    ports:
      - "${SERVER_PORT:-3000}:3000"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      - QR_DEFAULT_COLOR=${QR_DEFAULT_COLOR:-#000000}
      - RUST_LOG=info
    restart: unless-stopped
